image: Ubuntu2204

stack: node 20

branches:
  only:
    - master
    - main

cache: off

install:
  - npm install

build: off

build_script:
  - npm run build 

test_script:
  - npm run lint

test_script:
  - npm run e2e

deploy_script:
  - git config --global credential.helper store
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com
  - echo "https://$GH_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - npx push-dir --dir=dist --branch=gh-pages --force --verbose
